apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
- path: patch-ingress.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: test-ing
- path: patch-deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: test-api